package Laboratorio1;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;

public class Alumnos extends javax.swing.JFrame {

    private Alumno[] alumnos = null;
    private int indiceActual;
    /**
     * Creates new form Alumnos
     */
    public Alumnos() {
        initComponents();
        this.setLocationRelativeTo(null);
        taRegistro.setEditable(false);
        btnAlta.setEnabled(false);
        btnBaja.setEnabled(false);
        btnModificar.setEnabled(false);
        btnMostrar.setEnabled(false);
        btnMostrarR.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        longitud = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtSemestres = new javax.swing.JTextField();
        txtPromedio = new javax.swing.JTextField();
        btnAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnMostrarR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taRegistro = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        mNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cSemestres = new javax.swing.JTextField();
        cPromedio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONTROL ALUMNOS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(180, 160, 130));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel1.setText("Ingresa el tamaño del arreglo:");

        btnAceptar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 0, 51));
        jButton9.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jButton9.setText("Regresar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setText("Ingresa el nombre:");

        jLabel3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel3.setText("Semestres Cursados:");

        jLabel4.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel4.setText("Cal.Promedio:");

        btnAlta.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnAlta.setText("Dar de alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnBaja.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnBaja.setText("Dar de baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnModificar.setText("Modificar semestres y promedio");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnMostrar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnMostrar.setText("Mostrar alumno");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnMostrarR.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnMostrarR.setText("Mostrar registros");
        btnMostrarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarRActionPerformed(evt);
            }
        });

        taRegistro.setColumns(20);
        taRegistro.setRows(5);
        jScrollPane1.setViewportView(taRegistro);

        jLabel5.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel5.setText("Nombre:");

        jLabel6.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel6.setText("Semestre M:");

        jLabel7.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel7.setText("Promedio M:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(65, 65, 65)
                                .addComponent(txtPromedio, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre)
                                    .addComponent(txtSemestres, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAlta)
                            .addComponent(btnBaja)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAceptar)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMostrarR)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(mNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnModificar)
                            .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(cSemestres))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(cPromedio)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(longitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSemestres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAlta)
                        .addGap(26, 26, 26)
                        .addComponent(btnBaja)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(mNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMostrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(cSemestres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostrarR)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Desordenados or = new Desordenados();
        or.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        try
        {
            int tam = Integer.parseInt(longitud.getText());

            if (tam > 0)
            {
                if (alumnos == null)    
                {
                    alumnos = new Alumno[tam];
                }
                longitud.setEditable(false);
                longitud.setEnabled(false);
                btnAceptar.setEnabled(false);
                btnAlta.setEnabled(true);
                btnBaja.setEnabled(true);
                btnMostrarR.setEnabled(true);

            }
            else
            JOptionPane.showMessageDialog(null, "Ingresa un numero mayor a 0");
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "Ingresa un numero valido");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnMostrarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarRActionPerformed

        imprimirRegistros();
    }//GEN-LAST:event_btnMostrarRActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed

        darDeAlta();
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed

        darDeBaja();
    }//GEN-LAST:event_btnBajaActionPerformed


    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        modificarAlumno();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed

        buscarAlumnoYMostrarEnRegistro();
    }//GEN-LAST:event_btnMostrarActionPerformed
      
private void darDeAlta() {
    String nombre = txtNombre.getText().trim();
    String semestresText = txtSemestres.getText().trim();
    String promedioText = txtPromedio.getText().trim();

    if (nombre.isEmpty() || semestresText.isEmpty() || promedioText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, rellene todos los campos.");
        return;  
    }

    try 
    {
        int semestres = Integer.parseInt(semestresText); 
        double promedio = Double.parseDouble(promedioText); 

        if (semestres <= 0 || promedio < 0) {
            JOptionPane.showMessageDialog(this, "Los valores de semestres y promedio no son válidos.");
            return;
        }

        if (indiceActual < alumnos.length) {
            Alumno nuevoAlumno = new Alumno(nombre, semestres, promedio);
            alumnos[indiceActual] = nuevoAlumno;  
            indiceActual++; 
            btnModificar.setEnabled(true);
            btnMostrar.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Alumno dado de alta con éxito.");
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "No hay espacio para más alumnos.");
            limpiarCampos();
        }

    } catch (NumberFormatException e) 
    {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese valores válidos para semestres y promedio.");
    }
}

    private void darDeBaja() {
        String nombre = txtNombre.getText();
        boolean encontrado = false;
        
        if (nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese el nombre del alumno.");
        return;
    }

        for (int i = 0; i < indiceActual; i++) {
            if (alumnos[i].getNombre().equalsIgnoreCase(nombre)) {
                for (int j = i; j < indiceActual - 1; j++) {
                    alumnos[j] = alumnos[j + 1];
                }
                alumnos[indiceActual - 1] = null;  
                indiceActual--;
                JOptionPane.showMessageDialog(this, "Alumno dado de baja con éxito.");
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Alumno no encontrado.");
        }

        limpiarCampos();
    }

private void modificarAlumno() {
    String nombre = mNombre.getText().trim();

    if (nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa el nombre del alumno.");
        return;  
    }

    String semestresText = cSemestres.getText().trim();
    String promedioText = cPromedio.getText().trim();

    if (semestresText.isEmpty() || promedioText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa tanto los semestres como el promedio.");
        return;
    }

    try {
        int semestres = Integer.parseInt(semestresText);

        double promedio = Double.parseDouble(promedioText);

        boolean encontrado = false;
        for (int i = 0; i < indiceActual; i++) {
            if (alumnos[i].getNombre().equalsIgnoreCase(nombre)) {
                alumnos[i].setSemestresCursados(semestres);
                alumnos[i].setCalificacionPromedio(promedio);

                JOptionPane.showMessageDialog(this, "Datos del alumno modificados correctamente.");
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Alumno no encontrado.");
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa valores válidos para los semestres y el promedio.");
    }
}


    private void imprimirRegistros() {
        taRegistro.setText("");
        if (indiceActual == 0) {
            taRegistro.append("No hay registros de alumnos.");
        } else {
            taRegistro.setText("Nombre\tSemestres\tPromedio\n");
            for (int i = 0; i < indiceActual; i++) {
                taRegistro.append(alumnos[i].toString() + "\n");
            }
        }
    }
 
private void buscarAlumnoYMostrarEnRegistro() {
    String nombre = mNombre.getText().trim();

    if (nombre.isEmpty()) {
        taRegistro.setText("Por favor, ingrese el nombre del alumno.");
        return;  
    }

    boolean encontrado = false;
    for (int i = 0; i < indiceActual; i++) {
        if (alumnos[i].getNombre().equalsIgnoreCase(nombre)) { 
            taRegistro.setText("Nombre\tSemestres\tPromedio\n");
            taRegistro.append(alumnos[i].toString());
            encontrado = true;
            break;
        }
    }

    if (!encontrado) {
        taRegistro.setText("Alumno no encontrado.");
    }
}

    private void limpiarCampos() {
        txtNombre.setText("");
        txtSemestres.setText("");
        txtPromedio.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnMostrarR;
    private javax.swing.JTextField cPromedio;
    private javax.swing.JTextField cSemestres;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField longitud;
    private javax.swing.JTextField mNombre;
    private javax.swing.JTextArea taRegistro;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPromedio;
    private javax.swing.JTextField txtSemestres;
    // End of variables declaration//GEN-END:variables
}
