/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Laboratorio1;

import javax.swing.*;
public class Departamentos extends javax.swing.JFrame {
    private Departamento[] dep = null;
    private int indiceActual;

    /**
     * Creates new form Departamentos
     */
    public Departamentos() {
        initComponents();
        this.setLocationRelativeTo(null);
        taRegistro.setEditable(false);
        btnAlta.setEnabled(false);
        btnBaja.setEnabled(false);
        btnEmpleado.setEnabled(false);
        btnMedad.setEnabled(false);
        btnRegistros.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        longitud = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        mNombre = new javax.swing.JTextField();
        btnEmpleado = new javax.swing.JButton();
        txtSexo = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        txtEdad = new javax.swing.JTextField();
        btnRegistros = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnMedad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taRegistro = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        edadM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBaja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONTROL DEPARTAMENTOS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(180, 160, 130));

        jLabel5.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel5.setText("Buscar empleado:");

        btnAceptar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnEmpleado.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnEmpleado.setText("Mostrar");
        btnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadoActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 0, 51));
        jButton9.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jButton9.setText("Regresar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        btnRegistros.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnRegistros.setText("Mostrar empleados varones:");
        btnRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrosActionPerformed(evt);
            }
        });

        btnAlta.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnAlta.setText("Dar de alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setText("Nombre empleado:");

        btnMedad.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnMedad.setText("Actualizar edad:");
        btnMedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedadActionPerformed(evt);
            }
        });

        taRegistro.setColumns(20);
        taRegistro.setRows(5);
        jScrollPane1.setViewportView(taRegistro);

        jLabel6.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel6.setText("Edad M:");

        jLabel3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel3.setText("Sexo (M/F):");

        jLabel1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel1.setText("Ingresa el tamaño del arreglo:");

        jLabel4.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel4.setText("Edad:");

        btnBaja.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnBaja.setText("Dar de baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAceptar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtEdad)
                                            .addComponent(txtSexo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(64, 64, 64)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAlta)
                                            .addComponent(btnBaja))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(mNombre))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRegistros)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnMedad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(edadM, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 20, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(longitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAlta)
                        .addGap(26, 26, 26)
                        .addComponent(btnBaja)))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(mNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEmpleado)
                        .addGap(18, 18, 18)
                        .addComponent(btnMedad)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(edadM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(btnRegistros)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        try
        {
            int tam = Integer.parseInt(longitud.getText());

            if (tam > 0)
            {
                if (dep == null)
                {
                    dep = new Departamento[tam];
                }
                longitud.setEditable(false);
                longitud.setEnabled(false);
                btnAceptar.setEnabled(false);
                btnAlta.setEnabled(true);
                btnBaja.setEnabled(true);
            }
            else
            JOptionPane.showMessageDialog(null, "Ingresa un numero mayor a 0");
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "Ingresa un numero valido");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadoActionPerformed

        MostrarEmpleado();
    }//GEN-LAST:event_btnEmpleadoActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Desordenados or = new Desordenados();
        or.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrosActionPerformed

        obtenerEmpleadosPorSexo("Hombre", taRegistro);
    }//GEN-LAST:event_btnRegistrosActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed

        darDeAlta();
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnMedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedadActionPerformed

        modificarEmpleado();
    }//GEN-LAST:event_btnMedadActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed

        darDeBaja();
    }//GEN-LAST:event_btnBajaActionPerformed

    
    private void darDeAlta() {
    String nombre = txtNombre.getText().trim();
    String sexo = txtSexo.getText().trim();
    String edad = txtEdad.getText().trim();

    if (nombre.isEmpty() || sexo.isEmpty() || edad.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, rellene todos los campos.");
        return; 
    }
    
    if (sexo.equals("m")) {
        sexo = "Hombre";
    } else if (sexo.equals("f")) {
        sexo = "Mujer";
    } else if (!sexo.equalsIgnoreCase("Hombre") && !sexo.equalsIgnoreCase("Mujer")) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese 'Hombre', 'Mujer', 'M' o 'F' en el campo de sexo.");
        return;
    }

    try {
        int ed = Integer.parseInt(edad);  


        if (indiceActual < dep.length) {
            Departamento nuevoE = new Departamento(nombre, sexo, ed);
            dep[indiceActual] = nuevoE;  
            indiceActual++;  
            btnEmpleado.setEnabled(true);
            btnMedad.setEnabled(true);
            btnRegistros.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Empleado dado de alta con éxito.");
        } else {
            JOptionPane.showMessageDialog(this, "No hay espacio para más empleados.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese valores válidos para la edad.");
    }

    limpiarCampos();
}
    
    private void darDeBaja() {
        String nombre = txtNombre.getText();
        boolean encontrado = false;
        
        if (nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese el nombre del empleado.");
        return;
    }

        for (int i = 0; i < indiceActual; i++) {
            if (dep[i].getNombre().equalsIgnoreCase(nombre)) {
                for (int j = i; j < indiceActual - 1; j++) {
                    dep[j] = dep[j + 1];
                }
                dep[indiceActual - 1] = null;
                indiceActual--;
                JOptionPane.showMessageDialog(this, "Empleado dado de baja con éxito.");
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Empleado no encontrado.");
        }

        limpiarCampos();
    }
    
    
    private void MostrarEmpleado() {
    String nombre = mNombre.getText().trim();

    if (nombre.isEmpty()) {
        taRegistro.setText("Por favor, ingrese el nombre del Empleado.");
        return; 
    }

    boolean encontrado = false;
    for (int i = 0; i < indiceActual; i++) {
        if (dep[i].getNombre().equalsIgnoreCase(nombre)) {
            taRegistro.setText("Nombre: " + dep[i].getNombre() +
                "\tSexo: " + dep[i].getSexo() +
                "\tEdad: " + dep[i].getEdad());
            encontrado = true;
            break;
        }
    }

    if (!encontrado) {
        taRegistro.setText("Empleado no encontrado.");
    }
}
    
    private void modificarEmpleado() {
    String nombre = mNombre.getText().trim();

    if (nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa el nombre del Empleado.");
        return;
    }

    String edadtxt = edadM  .getText().trim();

    if (edadtxt.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa la edad.");
        return;
    }

    try {
        int ed = Integer.parseInt(edadtxt);

        boolean encontrado = false;
        for (int i = 0; i < indiceActual; i++) {
            if (dep[i].getNombre().equalsIgnoreCase(nombre)) {  // Comparación insensible a mayúsculas/minúsculas
                dep[i].setEdad(ed);

                JOptionPane.showMessageDialog(this, "Edad modificada.");
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Empleado no encontrado.");
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa valores válidos parala edad.");
    }
}
    
    
    public void obtenerEmpleadosPorSexo(String sexoBuscado, JTextArea taRegistro) {
    if (sexoBuscado.equalsIgnoreCase("M")) {
        sexoBuscado = "Hombre";
    } else if (sexoBuscado.equalsIgnoreCase("F")) {
        sexoBuscado = "Mujer";
    }

    boolean hayEmpleados = false; 

    taRegistro.setText("");

    for (Departamento d : dep) {
        if (d != null && d.getSexo().equalsIgnoreCase(sexoBuscado)) {
            String sexoM = d.getSexo().equalsIgnoreCase("Hombre") ? "M" : "F";
            taRegistro.append("Nombre: " + d.getNombre() + ", Sexo: " + sexoM + ", Edad: " + d.getEdad() + "\n");
            hayEmpleados = true; 
        }
    }

    if (!hayEmpleados) {
        taRegistro.setText("No hay registros de empleados con sexo: " + sexoBuscado);
    }
}

    private void limpiarCampos() {
        txtNombre.setText("");
        txtSexo.setText("");
        txtEdad.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnEmpleado;
    private javax.swing.JButton btnMedad;
    private javax.swing.JButton btnRegistros;
    private javax.swing.JTextField edadM;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField longitud;
    private javax.swing.JTextField mNombre;
    private javax.swing.JTextArea taRegistro;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables
}
