/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Laboratorio1;

import javax.swing.*;
public class Empresa extends javax.swing.JFrame {
    private Cempresa[] empresa = null;
    private int indiceActual;
    

    /**
     * Creates new form Empresa
     */
    public Empresa() {
        initComponents();
        this.setLocationRelativeTo(null);
        taRegistro.setEditable(false);
        btnAlta.setEnabled(false);
        btnBaja.setEnabled(false);
        btnMoroso.setEnabled(false);
        btnCliente.setEnabled(false);
        btnRegistros.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        longitud = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        btnAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnRegistros = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taRegistro = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        mNombre = new javax.swing.JTextField();
        btnMoroso = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONTROL EMPRESA");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(180, 160, 130));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel1.setText("Ingresa el tamaño del arreglo:");

        btnAceptar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 0, 51));
        jButton9.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jButton9.setText("Regresar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setText("Nombre cliente:");

        jLabel3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel3.setText("Telefono:");

        jLabel4.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel4.setText("Saldo:");

        btnAlta.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnAlta.setText("Dar de alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnBaja.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnBaja.setText("Dar de baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        btnCliente.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnCliente.setText("Mostrar Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnRegistros.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnRegistros.setText("Mostrar registros");
        btnRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrosActionPerformed(evt);
            }
        });

        taRegistro.setColumns(20);
        taRegistro.setRows(5);
        jScrollPane1.setViewportView(taRegistro);

        jLabel5.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel5.setText("Cliente:");

        btnMoroso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moroso", "No moroso" }));
        btnMoroso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMorosoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel8.setText("Estado Moroso:");

        jLabel6.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel6.setText("Modificar Estado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSaldo)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBaja)
                            .addComponent(btnAlta)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAceptar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(35, 35, 35)
                                        .addComponent(btnMoroso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistros)
                            .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(mNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel6)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(longitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAceptar))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlta))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btnBaja)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(btnMoroso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(71, 71, 71)
                        .addComponent(btnCliente)
                        .addGap(39, 39, 39)
                        .addComponent(btnRegistros)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        try
        {
            int tam = Integer.parseInt(longitud.getText());

            if (tam > 0)
            {
                if (empresa == null)
                {
                    empresa = new Cempresa[tam];
                }
                longitud.setEditable(false);
                longitud.setEnabled(false);
                btnAceptar.setEnabled(false);
                btnAlta.setEnabled(true);
                btnBaja.setEnabled(true);
                btnMoroso.setEnabled(true);

            }
            else
            JOptionPane.showMessageDialog(null, "Ingresa un numero mayor a 0");
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "Ingresa un numero valido");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Desordenados or = new Desordenados();
        or.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed

        darDeAlta();
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed

        darDeBaja();
    }//GEN-LAST:event_btnBajaActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed

        MostrarCliente();
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrosActionPerformed

        imprimirRegistros();
    }//GEN-LAST:event_btnRegistrosActionPerformed

    private void btnMorosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMorosoActionPerformed

            actualizarEstadoMoroso();
    }//GEN-LAST:event_btnMorosoActionPerformed

    
    private void darDeAlta() {
    String nombre = txtNombre.getText().trim();
    String telefono = txtTelefono.getText().trim();
    String saldo = txtSaldo.getText().trim();

    if (nombre.isEmpty() || telefono.isEmpty() || saldo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, rellene todos los campos.");
        return;  
    }

    try {
        double sald = Double.parseDouble(saldo);  
        String morosoSeleccionado = btnMoroso.getSelectedItem().toString().trim();
        boolean esMoroso = morosoSeleccionado.equals("Moroso");


        if (indiceActual < empresa.length) {
            Cempresa nuevoR = new Cempresa(nombre, telefono, sald, esMoroso);
            empresa[indiceActual] = nuevoR;  
            indiceActual++; 
            btnCliente.setEnabled(true);
            btnRegistros.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Cliente dado de alta con éxito.");
        } else {
            JOptionPane.showMessageDialog(this, "No hay espacio para más clientes.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese valores válidos para el saldo.");
    }

    limpiarCampos();
}
    
    private void darDeBaja() {
        String nombre = txtNombre.getText();
        boolean encontrado = false;
        
        if (nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese el nombre del Cliente.");
        return;
    }

        for (int i = 0; i < indiceActual; i++) {
            if (empresa[i].getNombre().equalsIgnoreCase(nombre)) {
                for (int j = i; j < indiceActual - 1; j++) {
                    empresa[j] = empresa[j + 1];
                }
                empresa[indiceActual - 1] = null;
                indiceActual--;
                JOptionPane.showMessageDialog(this, "Cliente dado de baja con éxito.");
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Cliente no encontrado.");
        }

        limpiarCampos();
    }
    
    
    private void MostrarCliente() {
    String nombre = mNombre.getText().trim();

    if (nombre.isEmpty()) {
        taRegistro.setText("Por favor, ingrese el nombre del Cliente.");
        return; 
    }

    boolean encontrado = false;
    for (int i = 0; i < indiceActual; i++) {
        if (empresa[i].getNombre().equalsIgnoreCase(nombre)) {
            taRegistro.setText("Nombre: " + empresa[i].getNombre() +
                "\tTelefono: " + empresa[i].getTelefono() +
                "\tSaldo: " + empresa[i].getSaldo() +
                "\tEstado: " + empresa[i].getMoroso());
            encontrado = true;
            break;
        }
    }

    if (!encontrado) {
        taRegistro.setText("Cliente no encontrado.");
    }
}
    
    
    private void actualizarEstadoMoroso() {
    String nombre = mNombre.getText().trim();

    if (nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa el nombre del Empleado.");
        return;
    }

    String morosoSeleccionado = btnMoroso.getSelectedItem().toString().trim();

    if (morosoSeleccionado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona si el empleado es moroso o no.");
        return;
    }

    boolean esMoroso = morosoSeleccionado.equals("Moroso");

    boolean encontrado = false;
    for (int i = 0; i < indiceActual; i++) {
        if (empresa[i].getNombre().equalsIgnoreCase(nombre)) {  
            empresa[i].setMoroso(esMoroso); 

            JOptionPane.showMessageDialog(this, "Estado de moroso actualizado.");
            encontrado = true;
            break;
        }
    }

    if (!encontrado) {
        JOptionPane.showMessageDialog(this, "Empleado no encontrado.");
    }
}


    
    private void imprimirRegistros() {
        taRegistro.setText("");
        if (indiceActual == 0) {
            taRegistro.append("No hay registros de Clientes.");
        } else {
            taRegistro.setText("Nombre\tTelefono\tSaldo\tEstadoMoroso\n");
            for (int i = 0; i < indiceActual; i++) {
                taRegistro.append(empresa[i].toString() + "\n");
            }
        }
    }
    
    private void limpiarCampos() {
        txtNombre.setText("");
        txtTelefono.setText("");
        txtSaldo.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnCliente;
    private javax.swing.JComboBox<String> btnMoroso;
    private javax.swing.JButton btnRegistros;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField longitud;
    private javax.swing.JTextField mNombre;
    private javax.swing.JTextArea taRegistro;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
