package Laboratorio2;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
public class BusBinaria extends javax.swing.JFrame {
    
    private static int i = 0;
    private static int arr[];
    private static StringBuilder elementosString = new StringBuilder();

    /**
     * Creates new form BusBinaria
     */
    public BusBinaria() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnOrdenar.setEnabled(false);
        BusElemento.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        MostrarOr = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ElementosIng = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        tamaño = new javax.swing.JTextField();
        MostrarDes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Elementos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Element = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        MosPos = new javax.swing.JTextField();
        BusElemento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BUSQUEDA BINARIA");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel4.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Arreglo desordenado");

        jLabel5.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Arreglo Ordenado");

        btnAceptar.setBackground(java.awt.SystemColor.activeCaption);
        btnAceptar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        MostrarOr.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        MostrarOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarOrActionPerformed(evt);
            }
        });

        btnInsertar.setBackground(java.awt.SystemColor.activeCaption);
        btnInsertar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnOrdenar.setBackground(java.awt.SystemColor.activeCaption);
        btnOrdenar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnOrdenar.setText("Mostrar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Elementos: ");

        jLabel1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingresa el tamaño del arreglo:");

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jButton4.setText("Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamañoActionPerformed(evt);
            }
        });

        MostrarDes.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        MostrarDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarDesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingresa los elementos de uno en uno:");

        Elementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElementosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Elemento a Buscar:");

        jLabel7.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Posicion del elemento: ");

        MosPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MosPosActionPerformed(evt);
            }
        });

        BusElemento.setBackground(java.awt.SystemColor.activeCaption);
        BusElemento.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        BusElemento.setText("Buscar");
        BusElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusElementoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BusElemento)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Element, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(MosPos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(76, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(MostrarDes, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MostrarOr, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(218, 218, 218)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(btnOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(163, 163, 163))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Elementos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInsertar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ElementosIng, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAceptar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Elementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ElementosIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MostrarDes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MostrarOr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Element, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(MosPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BusElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        try
        {
            int tam = Integer.parseInt(tamaño.getText());

            if (tam > 0)
            {
                arr = new int[tam];
                tamaño.setEnabled(false);
                btnAceptar.setEnabled(false);
            }
            else
            //JOptionPane.showMessageDialog(null, "Ingresa un numero mayor a 0");
            tamaño.setText("No valido");

        }
        catch(NumberFormatException ex)
        {
            //JOptionPane.showMessageDialog(null, "Ingresa un numero valido");
            tamaño.setText("No valido");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void MostrarOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarOrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarOrActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed

        try
        {
            int elemento = Integer.parseInt(Elementos.getText());

            if (i < arr.length)
            {
                arr[i] = elemento;
                i++;

                if (i == 1)
                {
                    elementosString.append(elemento);
                }
                else
                {
                    elementosString.append(", ").append(elemento);
                }

                ElementosIng.setText(elementosString.toString());

                Elementos.setText("");

                if (i == arr.length)
                {
                    //JOptionPane.showMessageDialog(null, "Arreglo Completado");
                    btnInsertar.setEnabled(false);
                    Elementos.setEnabled(false);
                    btnOrdenar.setEnabled(true);
                    ElementosIng.setEditable(false);
                }
            }
        }
        catch(NumberFormatException ex)
        {
            Elementos.setText("No valido");
            //JOptionPane.showMessageDialog(null, "Ingresa un elemento valido para el arreglo");
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed

        int tam = Integer.parseInt(tamaño.getText());

        MostrarDes.setText(ElementosIng.getText());
        MostrarDes.setEditable(false);

        /*  */

        String sal = "";
        burbuja(arr, tam);
        for(int j = 0; j < tam; j++)
        {
            if (j == tam - 1)
            {
                sal += arr[j];
            }
            else
            sal += arr[j] + ", ";
        }
        MostrarOr.setText(sal);
        MostrarOr.setEditable(false);
        BusElemento.setEnabled(true);
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Busquedas or = new Busquedas();
        elementosString.setLength(0);
        i = 0;
        or.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamañoActionPerformed

    private void MostrarDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarDesActionPerformed

    }//GEN-LAST:event_MostrarDesActionPerformed

    private void ElementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElementosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ElementosActionPerformed

    private void MosPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MosPosActionPerformed

    }//GEN-LAST:event_MosPosActionPerformed

    private void BusElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusElementoActionPerformed

        try
        {
            int tam = Integer.parseInt(tamaño.getText());
            int elemento = Integer.parseInt(Element.getText());
            Bbinaria(arr, tam, elemento);
        }
        catch(NumberFormatException ex)
        {
            MosPos.setText("No valido");
        }

        MosPos.setEditable(false);
    }//GEN-LAST:event_BusElementoActionPerformed

    public static void burbuja(int v[], int tam)
    {
        int temp;
	for (int i = 0; i < tam - 1; i++)
	{
            for(int k = 0; k < tam -1; k++)
            {
                if(v[k] > v[k + 1])
                {
                    temp = v[k];
                    v[k] = v[k + 1];
                    v[k + 1] = temp;
                }
            }
        }
    }
    
    public void Bbinaria(int v[], int tam, int elemento){
        int inicio = 0, centro = 0, fin = (tam - 1);
        boolean band  = false;
        String s = "";
        while((inicio <= fin) && band == false)
        {
            centro = (int)(inicio + fin) / 2;
            if (elemento == v[centro])
            {
                band = true;
            }
            else
            {
                if (elemento < v[centro])
                {
                    fin--;
                }
                else
                    inicio++;
            }     
        }
        if (band == true)
        {
            s += centro;
            MosPos.setText(s);
        }
        else
            MosPos.setText("No existe");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BusElemento;
    private javax.swing.JTextField Element;
    private javax.swing.JTextField Elementos;
    private javax.swing.JTextField ElementosIng;
    private javax.swing.JTextField MosPos;
    private javax.swing.JTextField MostrarDes;
    private javax.swing.JTextField MostrarOr;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tamaño;
    // End of variables declaration//GEN-END:variables
}
